# Generated by Django 5.0.7 on 2024-07-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departments', '0002_initial'),
        ('users', '0002_speedtest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['department'], name='users_custo_departm_fce76f_idx'),
        ),
    ]
