# Generated by Django 5.0.7 on 2024-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest',
            name='source',
            field=models.CharField(max_length=10),
        ),
    ]
